### ISSUE TITLE
Omitted Words

### ISSUE THREAD

**Issue by leo-bonfim** [nguyenq/tess4j#138]
I'm trying to recognize a text using "TessBaseAPISetPageSegMode(handle, TessPageSegMode.PSM_AUTO_OSD);" but, in some cases, the result isn't complete. it's like some text was omitted. How can I get all of words using this techniques, or i realy have to use the Tesseract class? (ITesseract instance = new Tesseract())

**Comment by nguyenq** [comment]
The library only returns what was processed and output by the Tesseract engine. You can try different PSM or use your own page segmentation techniques. But many times, due to the quality of the image, the engine could miss some regions of text; so image preprocessing may be needed.

The `Tesseract` class is nothing more than a convenient wrapper of some common methods in the lower `TessAPI` class. You can use in any way which works for you.

**Comment by leo-bonfim** [comment]
I get it.. Thx a lot!
