### ISSUE TITLE
Can this lib be used in android?

### ISSUE THREAD

**Issue by softboy99** [nguyenq/tess4j#189]
Can this lib be used in android?

**Comment by nguyenq** [comment]
At one time, JNA did not support Android, but looks like it does now.

https://github.com/java-native-access/jna/tree/master/lib/native

That said, it seems that BufferedImage class, which is used by Tess4J, was not supported on Android platform.

https://stackoverflow.com/questions/13198909/ocr-for-android-application-tess4j
https://stackoverflow.com/questions/33210065/how-can-i-import-java-awt-image-bufferedimage-in-android-studio

That was then. We do not know if anything has changed since.

You can use Tess-Two for Android.
