### ISSUE TITLE
PdfBox has different output than GS

### ISSUE THREAD

**Issue by Abu-Abdullah** [nguyenq/tess4j#199]
Hi,

i have been testing both PdfBox / GS but noticed a big difference in some files.

PdfBox gives better images than GS

test file:
https://drive.google.com/file/d/193Dt1BC1VIOHbKcGKNiIMXg-vMhspQ7R/view?usp=sharing

page 10 (got it from the temp folder) in case of pdfbox
![workingimage0010-pdfbox](https://user-images.githubusercontent.com/2059463/96401296-ef00fd80-11e3-11eb-842f-00d8a438b21c.png)

page 10 in case of gs
![workingimage0010](https://user-images.githubusercontent.com/2059463/96401316-fa542900-11e3-11eb-82d6-135d97d706f8.png)

as you can see, the image in pdfbox is scaled correctly where in gs, it adds a white margin. i want to use the gs since it is much faster but it seems the results is different in both of them resulting in different accuracy of the output text

in addition, it seems the resolution is different in both of them

**Comment by nguyenq** [comment]
While the output images are not identical (due to using different underlying technologies between the two libraries), the OCR results are comparable, based on our limited testing.

https://github.com/nguyenq/tess4j/pull/60

The resolution of the output images is fixed to 300 DPI, which is considered optimal for OCR success rates.

You cetainly can tweak them in your own implementation, or even use a different PDF library of your choice, and send the result images to Tesseract for recognition.

**Comment by Abu-Abdullah** [comment]
ok, i was trying to play with the PdfGsUtilities code to see if i can scale the image but it seems this is the normal behaviour of GS

since there are many PDF libraries and configurations (and expectation), it might be better to remove these libraries from tess4j dependency list (currently 22 in maven which i guess a lot) as the focus is not into this direction. the current code can be moved to examples and works as excellent reference
