### ISSUE TITLE
"createDocumentsWithResults(...)" fails when "filename" is null

### ISSUE THREAD

**Issue by Mararsh** [nguyenq/tess4j#234]
My codes fail to do OCR after upgrade tess4j from v6.4.4 to v6.5.3.

The problem is caused by parameter "filename" of following method:
`public OCRResult createDocumentsWithResults(BufferedImage bi, String filename, String outputbase, List<ITesseract.RenderedFormat> formats, int pageIteratorLevel) throws TesseractException`

Null works for "filename" in  v6.4.4 while null does not work in v6.5.3.
I am not sure whether this parameter is useful when BufferedImage is the source image.

My workaround is fill value of "filename" as value of "outputbase".

**Comment by nguyenq** [comment]
The library does not have those versions.

The code for that method has not changed. If the exception occurs now, we're not sure where and how a NULL value handling has changed in JNA and Tesseract OCR code.

`filename` inside Tesseract is passed to `SetInputName` method and is needed only for training and loading a UNLV zone file, according Tesseract documentation. So if you're not using it, pass an empty string instead of null.

**Comment by Mararsh** [comment]
Sorry. I wrote wrong versions.
Should be: upgrade from 4.4.0 from 5.3.0

**Comment by nguyenq** [comment]
Please check out the fix and let us know.

Thanks.

**Comment by nguyenq** [comment]
Please check out the fix and let us know.

Thanks.
