### ISSUE TITLE
Tesseract1Test.testCreateDocuments() passes with created document of 1348 bytes

### ISSUE THREAD

**Issue by Flumen** [nguyenq/tess4j#43]
The output files for Tesseract1Test.testCreateDocuments() are 1348 bytes and is an invalid pdf.

Steps to reproduce:
1. Open your workspace
2. Run Tesseract1Test.testCreateDocuments()
4. check file size of test/test-results/docrenderer1-1.pdf
3. Open test/test-results/docrenderer1-1.pdf

Expected results:
file size of docrenderer1-1.pdf is larger than 1348 bytes and can open in Adobe reader successfully.

Actual results:
File size of test/test-results/docrenderer1-1.pdf is exactly 1348 bytes and cannot be opened.

Dropbox links to relevant files:
docrenderer1-1.pdf output file [https://www.dropbox.com/s/bbkp67h37ksd4tu/docrenderer1-1.pdf?dl=0](url)
updated Tesseract1Test.java to check file size [https://www.dropbox.com/s/iu24h6ps1ij4i9m/Tesseract1Test.java?dl=0](url)

**Comment by nguyenq** [comment]
Boths provided links are broken.

Did you have success with `Tesseract1` API counterpart `Tesseract`?

**Comment by Flumen** [comment]
Yes, the TesseractTest.testCreateDocuments() works great. I will switch to that.

Here are the updated links:
[docrenderer1-1.pdf](https://www.dropbox.com/s/bbkp67h37ksd4tu/docrenderer1-1.pdf?dl=0)
[Tesseract1Test.java](https://www.dropbox.com/s/iu24h6ps1ij4i9m/Tesseract1Test.java?dl=0)

**Comment by nguyenq** [comment]
On Linux, under certain circumstances, sometimes we saw that `Tesseract1` API was unable to find `pdf.ttf` file under `tessdata` folder during creation of searchable PDF, which would result in broken PDF output. The root cause could be some where in JNA Direct Mapping implementation, but we did not have the resource to really dig deep into it. The workaround is to use the regular `Tesseract` API.
